language: android
android:
 components:
    - tools
    - android-26
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository 
before_install:
  mkdir -p "$ANDROID_SDK/licenses"
echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_SDK/licenses/android-sdk-license"
echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_SDK/licenses/android-sdk-preview-license"

jdk: oraclejdk8    
licenses:
    - android-sdk-license-.+
    - '.+'
script:
    - chmod +x gradlew
    - ./gradlew testDebug
